# Generated by Django 5.2 on 2025-05-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_recipe_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='student', 
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact', models.IntegerField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('is_check', models.BooleanField(default=True)),
            ],
        ),
    ]
